  export const PODCAST_GENRES = [
  { id: 1301, name: "Arts" },
  { id: 1302, name: "Business" },
  { id: 1303, name: "Comedy" },
  { id: 1305, name: "Education" },
  { id: 1306, name: "Fiction" },
  { id: 1307, name: "Games & Hobbies" },
  { id: 1308, name: "Government" },
  { id: 1309, name: "Health & Fitness" },
  { id: 1310, name: "History" },
  { id: 1311, name: "Kids & Family" },
  { id: 1314, name: "Music" },
  { id: 1315, name: "News" },
  { id: 1316, name: "Religion & Spirituality" },
  { id: 1317, name: "Science" },
  { id: 1318, name: "Sports" },
  { id: 1320, name: "TV & Film" },
  { id: 1321, name: "True Crime" },
  { id: 1323, name: "Technology" },
  { id: 1324, name: "Society & Culture" },
]; 
export const MUSIC_GENRES = [
  { id: 20, name: "Alternative" },
  { id: 1197, name: "Arabic" },
  { id: 29, name: "Anime" },
  { id: 2, name: "Blues" },
  { id: 1122, name: "Brazilian" },
  { id: 4, name: "Children's Music" },
  { id: 1232, name: "Chinese" },
  { id: 22, name: "Christian & Gospel" },
  { id: 5, name: "Classical" },
  { id: 3, name: "Comedy" },
  { id: 6, name: "Country" },
  { id: 17, name: "Dance" },
  { id: 50000063, name: "Disney" },
  { id: 25, name: "Easy Listening" },
  { id: 7, name: "Electronic" },
  { id: 28, name: "Enka" },
  { id: 50, name: "Fitness & Workout" },
  { id: 1289, name: "Folk" },
  { id: 50000064, name: "French Pop" },
  { id: 50000068, name: "German Folk" },
  { id: 50000066, name: "German Pop" },
  { id: 18, name: "Hip-Hop/Rap" },
  { id: 8, name: "Holiday" },
  { id: 1262, name: "Indian" },
  { id: 100000, name: "Christian & Gospel" },
  { id: 53, name: "Instrumental" },
  { id: 27, name: "J-Pop" },
  { id: 11, name: "Jazz" },
  { id: 52, name: "Karaoke" },
  { id: 30, name: "Kayokyoku" },
  { id: 1243, name: "Korean" },
  { id: 12, name: "Latino" },
  { id: 1291, name: "Marching" },
  { id: 13, name: "New Age" },
  { id: 1290, name: "Orchestral" },
  { id: 14, name: "Pop" },
  { id: 15, name: "R&B/Soul" },
  { id: 24, name: "Reggae" },
  { id: 21, name: "Rock" },
  { id: 10, name: "Singer/Songwriter" },
  { id: 16, name: "Soundtrack" },
  { id: 50000061, name: "Spoken Word" },
  { id: 23, name: "Vocal" },
  { id: 19, name: "World" },
];